### PR TITLE
Add Zapier, Java SDk to integrations section

### PR DESCRIPTION
**Pull request by cjscheller**
Adds Zapier and Java SDK to integrations section of docs. 

Currently in _Draft_ status as not sure we want to roll this out until the integrations are a bit more polished/available - thoughts?

### CODE REVIEW

**Comment by tim-davenport** [comment]
I think it's good to have this PR in the works - I mean, yes, we could always polish a bit more but then again it might get more people interested in actually using the Zapier integration and contributing toward the Java SDK etc. so I definitely don't think it would be a bad idea to put this out at all.

**Comment by cjscheller** [comment]
Ok good point, agreed and will roll out. No reason for us to limit that at this point, especially since we're not sure who or how could use it. 

In support of that point, it seems like our Ruby gem is getting a solid amount of usage. According to the Rubygems [directory page](https://rubygems.org/gems/digitalhumani), it's already been downloaded 360+ times and the new version that was just released a few hours ago nearly 40 times. No way to say how legitimate that traffic is, but still good to see.

**Comment by tim-davenport** [comment]
Yup - that sounds promising! Along similar lines, I was hoping to push the Java SDK to Maven once some of the pre-reqs have been addressed. There's actually Github action for that, so should be pretty easy to do as a CI/CD piece

**Comment by cjscheller** [comment]
Sounds great. I added an action for the Ruby SDK as well, and still finalizing the CI/CI pipeline - so we can add those in parallel

**Pull request merged**
